### ISSUE TITLE
fit_incremental_angmix throws "tcltk could not be loaded" warning

### ISSUE THREAD

**Issue by JonathanEricson** [c7rishi/BAMBI#2]
**Describe the bug**
This package is really exciting, many thanks for your efforts on it. 
Unfortunately fit_incremental_angmix throws the following warning message(s):

Warning messages:
1: In (function (model = "vmsin", data, ncomp, cov.restrict = "NONE",  :
  tcltk could not be loaded. 'show.progress' was set to FALSE.
2: In (function (model = "vmsin", data, ncomp, cov.restrict = "NONE",  :
  tcltk could not be loaded. 'show.progress' was set to FALSE.
3: In (function (model = "vmsin", data, ncomp, cov.restrict = "NONE",  :
  tcltk could not be loaded. 'show.progress' was set to FALSE.

**To Reproduce**
1. Steps to reproduce the behavior:
2. # install homebrew on OS: https://brew.sh/
3. # install Install XCode from the App Store on OS
4. # install XCode command line tools: https://stackoverflow.com/questions/9329243/xcode-install-command-line-tools
5. #      Terminal>> xcode-select --install
6. #      Terminal>> brew install gsl
7. # install.packages("gsl")
8. # install gfortran for Mojave https://github.com/fxcoudert/gfortran-for-macOS/releases
9. # install.packages("RcppArmadillo")
10. # install.packages("BAMBI")
11. # install X11 https://www.xquartz.org/ so that tcltk works

**Expected behavior**
No Warning message

**Desktop (please complete the following information):**
 - OS: Mac Mojave Version 10.14.6
 - R Studio Version 1.2.1335
 - R Version 3.6.1 (2019-07-05)

**Additional context**
- X11 is installed
- install.packages("tcltk") works fine
- require(tcltk) works fine

**Question**
It seems that tcltk is installed on my system, and that R and R Studio recognize that it's installed. How essential is tcltk to the output of fit_incremental_angmix, and other functions in the package? Is tcltk needed only for graphical display of results or progress indication?

**Comment by c7rishi** [comment]
Thanks for the detailed report.  fit_angmix (which is the main MCMC sampler in BAMBI, and is called recursively in fit_incremental_angmix) throws that warning when it is unable to use tcltk::tkProgressBar. Could you check if the following script runs? 

```
pb <- tcltk::tkProgressBar(title = "Progress", min = 0, max = 10)
for(i in 1:10) { 
  Sys.sleep(1)
  tcltk::setTkProgressBar(pb, i)
}
close(pb)
```

BAMBI uses tcltk::tkProgressbar to show progress of the MCMC run. No other function depends on tcltk, and the progress bar does not affect the results/visualizations in any way. So your analysis will remain unaffected, even if tcltk fails to function properly!

**Comment by JonathanEricson** [comment]
Thanks for your reply!

>tcltk::tkProgressBar(title = "Progress", min = 0, max = 10)

Results in error:

Error in structure(.External(.C_dotTclObjv, objv), class = "tclObj") : 
  [tcl] invalid command name "toplevel".

**Comment by c7rishi** [comment]
Right, so tcltk::tkProgressBar is not functioning properly, which unfortunately means that the GUI progress bar won't show up in fit_angmix or in fit_incremental_angmix. I'm closing this issue since this is a problem with tcltk, and since this doesn't affect the MCMC sampling.
